export class Product {
    constructor(
        public id?:number,
        public mainCategory?: number,
        public category?: number,
        public subCategory?: number,
        public productName?: string,
        public brandName?: string,
        public manufacturerName?: string,
        public productCode?: number,
        public startRating?: boolean,
        public productSRNumber?: string,
        public productPrice?: number,
        public discountPrice?: number,
        public emiOptiions?: boolean,
        public avibilityStatus?: boolean,
       // public productQuantity?: number [],
        public descripition?: string,
        public relatedProduct?: boolean,
        //public selectedSize?: string [],
        public productSize?: string,
        public itemWeight?: string,
     // public productListImage?: string,
        public isActive?: number,
        public sizeList?:any[],
        public productMainImage?: string,
        public selectedSize?:any[],
        public multi?:any[],
        public selectedCheck?:Boolean,
        public isNewArrival?:boolean,
        public isBestProduct?:boolean,
        public isHot?:boolean,
        public isOnSale?:boolean,
    ) {
    }
}